<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="exposed.json" />
    <InternalsVisibleTo Include="LupiraAssistantBff.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lupira.Bff.Auth" Version="0.2.1" />
    <PackageReference Include="Lupira.Bff.Proxy" Version="0.2.1" />
    <PackageReference Include="Lupira.Build" Version="1.1.0" PrivateAssets="all" />
    <PackageReference Include="Lupira.Hosting.Defaults" Version="0.1.0" />
    <PackageReference Include="Lupira.Hosting.Health" Version="0.1.0" />
    <PackageReference Include="Lupira.Hosting.Observability" Version="0.1.1" />
  </ItemGroup>

</Project>
